import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/tanstackProvider";
import Topbar from "@/components/topbar";
import Footer from "@/components/footer";
import React from "react";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "TNC - Nextjss",
    template: "%s | HeddaNime",
  },
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <header>
            <Topbar />
          </header>
          <div>{children}</div> 
          <footer>
            <Footer />
          </footer>
        </TanstackProvider>
      </body>
    </html>
  );
}