import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/tanstackProvider";
import Topbar from "@/components/topbar";
import Footer from "@/components/footer";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "TNC - Nextjss",
    template: "%s | HeddaNime",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  dashboard,
}: Readonly<{
  children: React.ReactNode;
  dashboard: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <header>
            <Topbar />
          </header>
          <div>{children} </div>
          <div>{dashboard}</div>
          <footer>
            <Footer />
          </footer>
        </TanstackProvider>
      </body>
    </html>
  );
}
